@import "tailwindcss";

:root { --ink:#1d2926; --muted:#69736f; --paper:#f4f2ec; --card:#fffefb; --line:#deddd7; --green:#335c52; --green-soft:#dfe9e5; --amber:#c88b45; --danger:#a64c42; }
* { box-sizing:border-box; }
html { background:var(--paper); }
body { margin:0; color:var(--ink); background:var(--paper); font-family:-apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic UI",sans-serif; }
button,input,select { font:inherit; }
button { cursor:pointer; }
.app-shell { min-height:100dvh; padding-bottom:88px; }
.topbar { position:sticky; top:0; z-index:20; display:flex; align-items:center; justify-content:space-between; padding:18px max(18px,calc((100vw - 980px)/2)); background:rgba(244,242,236,.92); backdrop-filter:blur(16px); border-bottom:1px solid rgba(222,221,215,.8); }
.topbar h1 { margin:0; font-size:22px; letter-spacing:.02em; }
.eyebrow { margin:0 0 4px; color:var(--green); font-size:11px; font-weight:800; letter-spacing:.16em; }
.weather-pill { display:flex; align-items:center; gap:9px; padding:9px 13px; border-radius:18px; background:var(--card); border:1px solid var(--line); box-shadow:0 4px 18px rgba(27,42,37,.06); }
.weather-pill>span { color:var(--amber); font-size:22px; }.weather-pill div{display:grid}.weather-pill strong{font-size:14px}.weather-pill small{font-size:10px;color:var(--muted)}
.content { max-width:980px; margin:0 auto; padding:24px 18px 48px; }
.stack { display:grid; gap:20px; }
.hero-card { display:flex; justify-content:space-between; gap:24px; align-items:center; padding:28px; border-radius:28px; color:white; background:linear-gradient(135deg,#294e46,#557a70); box-shadow:0 20px 45px rgba(41,78,70,.18); }
.hero-card h2,.section-title h2,.completion h2 { margin:0; font-size:clamp(24px,5vw,34px); letter-spacing:-.03em; }.hero-card p:not(.eyebrow){margin:8px 0 0;color:#e4eeea}.hero-card .eyebrow{color:#bcd5cc}
.today-weather { min-width:110px; display:grid; text-align:right; }.today-weather b{font-size:14px}.today-weather strong{font-size:34px}.today-weather small{color:#d8e6e1}
.panel,.shoe-card,.item-card,.completion,.stats,.timeline,.empty { background:var(--card); border:1px solid var(--line); border-radius:24px; box-shadow:0 7px 28px rgba(29,41,38,.055); }
.panel { padding:22px; }.panel h3{margin:0 0 18px;font-size:18px}
.form-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:14px; }.form-grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}
label { display:grid; gap:7px; color:var(--muted); font-size:12px; font-weight:700; }
input,select { width:100%; min-height:44px; padding:10px 12px; color:var(--ink); background:white; border:1px solid var(--line); border-radius:12px; outline:none; } input:focus,select:focus{border-color:var(--green);box-shadow:0 0 0 3px var(--green-soft)}
.primary,.secondary,.danger,.icon-button { min-height:44px; padding:10px 17px; border-radius:14px; font-weight:750; border:1px solid transparent; }
.primary { color:white; background:var(--green); }.primary:disabled{opacity:.45}.primary.compact{min-height:40px;padding:8px 14px}.secondary{color:var(--ink);background:white;border-color:var(--line)}.danger{color:var(--danger);background:#fff3f1;border-color:#eccac5}.icon-button{width:42px;padding:0;background:#f0eee8;border-color:var(--line);font-size:22px}
.panel>.primary { width:100%; margin-top:18px; }.yesterday{margin-top:14px;padding:10px 12px;border-radius:12px;background:#f3f1eb;color:var(--muted);font-size:12px}
.section-title { display:flex; align-items:end; justify-content:space-between; gap:20px; }.section-title h3{margin:0;font-size:25px}.section-title>span{color:var(--muted);font-size:12px}
.recommendations { display:grid; gap:14px; }.shoe-card { position:relative; display:grid; grid-template-columns:52px 150px 1fr; gap:18px; padding:16px; overflow:hidden; }.shoe-card.rank-1{border-color:#a8c2b8;box-shadow:0 15px 38px rgba(51,92,82,.12)}.rank{display:grid;place-items:center;width:38px;height:38px;border-radius:50%;background:var(--green-soft);color:var(--green);font-weight:900;font-size:18px}.rank-1 .rank{color:white;background:var(--green)}
.item-photo { width:100%; height:100%; min-height:110px; object-fit:cover; border-radius:16px; background:#eceae4; }.item-photo.placeholder{display:grid;place-items:center;color:#7c8782;font-size:38px}
.shoe-copy { display:grid;align-content:center;gap:9px}.score{display:flex;justify-content:space-between;align-items:center;gap:15px}.score b{font-size:20px}.score strong{color:var(--green);font-size:26px}.score small{font-size:11px}.shoe-copy p{margin:0;color:var(--muted);font-size:13px;line-height:1.55}.tags{display:flex;flex-wrap:wrap;gap:6px}.tags span{padding:5px 9px;border-radius:999px;background:#f0eee8;color:var(--muted);font-size:10px}.shoe-copy button{width:fit-content}
.completion { padding:38px; text-align:center; }.check{display:grid;place-items:center;width:64px;height:64px;margin:0 auto 18px;border-radius:50%;color:white;background:var(--green);font-size:32px}.completion>.primary{min-width:220px}.muted{color:var(--muted)}.outfit-row{display:grid;grid-template-columns:repeat(3,1fr);gap:13px;margin:28px 0}.outfit-row>div{display:grid;gap:6px;text-align:left}.outfit-row .item-photo{height:150px}.outfit-row small{color:var(--muted)}.reason-box{max-width:620px;margin:0 auto 24px;padding:16px;border-radius:16px;text-align:left;background:#f0eee8}.reason-box p{margin:7px 0 0;color:var(--muted)}
.segmented{display:grid;grid-template-columns:repeat(3,1fr);padding:4px;border-radius:16px;background:#e8e5de}.segmented button{padding:10px;border:0;border-radius:12px;background:transparent;color:var(--muted);font-weight:750}.segmented button.active{color:var(--ink);background:white;box-shadow:0 3px 12px rgba(30,40,36,.08)}
.master-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.item-card{display:grid;grid-template-columns:120px 1fr;gap:15px;padding:13px;text-align:left;cursor:pointer}.item-card .item-photo{height:120px}.item-card>div:last-child{display:grid;align-content:center;gap:6px}.item-card p,.item-card small{margin:0;color:var(--muted)}.item-card small{display:block}.card-title{display:flex;justify-content:space-between}.card-title span{color:var(--amber)}
.modal-backdrop{position:fixed;inset:0;z-index:50;display:grid;place-items:center;padding:18px;background:rgba(19,28,25,.48);backdrop-filter:blur(8px)}.editor{width:min(760px,100%);max-height:94dvh;padding:22px;overflow:auto;border-radius:28px;background:var(--card);box-shadow:0 30px 90px rgba(0,0,0,.24)}.editor-head{display:flex;justify-content:space-between;align-items:start}.editor-head h2{margin:0}.photo-stage{margin-top:18px}.photo-stage img,.photo-empty{width:100%;height:260px;border-radius:20px;object-fit:contain;background:#efede7}.photo-empty{display:grid;place-items:center;align-content:center;gap:6px;color:var(--muted)}.photo-empty span{font-size:42px}.photo-actions,.assist-box>div,.editor-actions{display:flex;gap:10px;flex-wrap:wrap}.photo-actions{margin:12px 0}.analysis-note{padding:10px 12px;border-radius:12px;background:var(--green-soft);color:var(--green);font-size:12px}.assist-box{margin-top:18px;padding:15px;border-radius:16px;background:#f0eee8}.assist-box p{margin:5px 0 12px;color:var(--muted);font-size:12px}.favorite{display:flex;align-items:center;margin:16px 0;font-size:14px;color:var(--ink)}.favorite input{width:auto;min-height:auto}.editor-actions{justify-content:flex-end;border-top:1px solid var(--line);padding-top:16px}
.timeline{padding:8px 20px}.timeline article{display:grid;grid-template-columns:100px 1fr;gap:15px;padding:17px 0;border-bottom:1px solid var(--line)}.timeline article:last-child{border-bottom:0}.timeline time{color:var(--muted);font-size:12px}.timeline div{display:grid;gap:4px}.timeline p,.timeline small{margin:0;color:var(--muted)}
.stats{display:grid;grid-template-columns:repeat(4,1fr);overflow:hidden}.stats div{display:grid;gap:3px;padding:22px;border-right:1px solid var(--line)}.stats div:last-child{border:0}.stats strong{font-size:28px;color:var(--green)}.stats span{font-size:11px;color:var(--muted)}
.ranking{display:grid;grid-template-columns:28px 52px 1fr auto;align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid var(--line)}.ranking:last-child{border:0}.ranking>.item-photo{min-height:52px;height:52px}.ranking>span{color:var(--green);font-weight:900}.ranking div{display:grid}.ranking small,.maintenance small{color:var(--muted)}.maintenance{display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid var(--line)}.maintenance div{display:grid}.maintenance span{align-self:center;padding:5px 9px;border-radius:999px;font-size:10px}.warning{color:#8a5b21;background:#f7e8d3}.ok{color:var(--green);background:var(--green-soft)}
.empty{display:grid;place-items:center;padding:50px;color:var(--muted)}.empty span{font-size:40px}.tabbar{position:fixed;left:50%;bottom:max(12px,env(safe-area-inset-bottom));z-index:30;display:grid;grid-template-columns:repeat(4,1fr);width:min(520px,calc(100% - 24px));padding:6px;transform:translateX(-50%);border:1px solid rgba(222,221,215,.85);border-radius:22px;background:rgba(255,254,251,.94);backdrop-filter:blur(18px);box-shadow:0 12px 40px rgba(29,41,38,.16)}.tabbar button{display:grid;place-items:center;gap:2px;padding:8px 4px;border:0;border-radius:16px;color:var(--muted);background:transparent;font-size:10px;font-weight:700}.tabbar button span{font-size:19px}.tabbar button.active{color:white;background:var(--green)}

@media(max-width:700px){.topbar{padding:14px 16px}.content{padding:18px 12px 42px}.hero-card{padding:22px;align-items:start}.hero-card p:not(.eyebrow){font-size:13px}.today-weather{min-width:82px}.form-grid,.form-grid.three{grid-template-columns:1fr}.shoe-card{grid-template-columns:36px 92px 1fr;gap:10px}.shoe-card .item-photo{min-height:92px}.score{display:grid}.score b{font-size:16px}.shoe-copy button{grid-column:1/-1;width:100%}.master-grid{grid-template-columns:1fr}.item-card{grid-template-columns:92px 1fr}.item-card .item-photo{height:92px}.outfit-row{gap:7px}.outfit-row .item-photo{height:100px}.outfit-row b{font-size:11px}.completion{padding:25px 13px}.stats{grid-template-columns:repeat(2,1fr)}.stats div:nth-child(2){border-right:0}.stats div:nth-child(-n+2){border-bottom:1px solid var(--line)}.editor{padding:17px;border-radius:24px}.photo-stage img,.photo-empty{height:220px}.editor-actions .primary{width:100%;order:-1}.timeline article{grid-template-columns:82px 1fr}.weather-pill{padding:7px 10px}.weather-pill>span{display:none}}
